/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationsIndexRouteImport } from './routes/conversations.index'
import { Route as ConversationsIdRouteImport } from './routes/conversations.$id'

const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConversationsRoute,
} as any)
const ConversationsIdRoute = ConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConversationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/observability': typeof ObservabilityRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/': typeof ConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/observability': typeof ObservabilityRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations': typeof ConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/observability': typeof ObservabilityRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/': typeof ConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/observability'
    | '/conversations/$id'
    | '/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/observability' | '/conversations/$id' | '/conversations'
  id:
    | '__root__'
    | '/'
    | '/conversations'
    | '/observability'
    | '/conversations/$id'
    | '/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationsRoute: typeof ConversationsRouteWithChildren
  ObservabilityRoute: typeof ObservabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/': {
      id: '/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof ConversationsRoute
    }
    '/conversations/$id': {
      id: '/conversations/$id'
      path: '/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ConversationsIdRouteImport
      parentRoute: typeof ConversationsRoute
    }
  }
}

interface ConversationsRouteChildren {
  ConversationsIdRoute: typeof ConversationsIdRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
}

const ConversationsRouteChildren: ConversationsRouteChildren = {
  ConversationsIdRoute: ConversationsIdRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
}

const ConversationsRouteWithChildren = ConversationsRoute._addFileChildren(
  ConversationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationsRoute: ConversationsRouteWithChildren,
  ObservabilityRoute: ObservabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
